### ISSUE TITLE
Introduce crowdin localization support

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-docs#22]
As we expand our localization efforts we must streamline the language process, crowdin will help with this.

**Comment by comradekingu** [comment]
@ImmaZoni Check out Weblate instead of going down the road of trying Crowdin.
Crowdin is closed source software only offered as a service. One that has lots of spying scripts.
It doesn't handle fuzzy strings correctly, and the preconfigured locales are wrong.
Moreover, it is not possible to browse multiple languages at once. In fact all strings are hidden when not logged in.

**Comment by ImmaZoni** [comment]
> @ImmaZoni Check out Weblate instead of going down the road of trying Crowdin.
> Crowdin is closed source software only offered as a service. One that has lots of spying scripts.
> It doesn't handle fuzzy strings correctly, and the preconfigured locales are wrong.
> Moreover, it is not possible to browse multiple languages at once. In fact all strings are hidden when not logged in.

thanks for the tip! I will check them out!

**Comment by ImmaZoni** [comment]
Issue closed with PR #189
