### ISSUE TITLE
Link to "Edit this page" is broken

### ISSUE THREAD

**Issue by EmilFattakhov** [subspace/subspace-docs#270]
As per Skyler's feedback on [Discord](https://discord.com/channels/864285291518361610/1156661042206752879), the "Edit this page" functionality is broken at the moment. 

With the introduction of CLRD support, the link to "edit" has become dependant on a selected language.

**Comment by jrwashburn** [comment]
@EmilFattakhov I don't think this is a good first issue, its solution will (if I understood things correctly) have larger impacts and someone closer to the build/deploy process should be consulted at least. I'm not sure who that might be. 

The edit link (on all pages) is pointing to the expected directory where the docusaurus/crowdin integration would put the localized version of the files. For the current edit button to be fixed, I think there are a few options.

1. Whoever runs the crowdin:sync script could also commit the localized versions to github after they are built and downloaded. Downside: that will introduce a source control conflict - should the latest versions of the documents be in github, or are they in crowdin? I don't think we want people using the edit button and making changes that will get overwritten by the next crowdin sync, although at least that could raise conflicts. The downside would be that whoever is trying to build and deploy may be faced with resolving conflicts in a language they do not know.

2. There are also integration options for [crowdin to integrate](https://support.crowdin.com/github-integration/) with the github repo, which may be better. It uses l10n instead if i18n folders, so that would probably drive some other changes to the build.

**Comment by EmilFattakhov** [comment]
Fixed by https://github.com/subspace/subspace-docs/pull/390
